name: chatapp
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.0
  google_sign_in: ^5.2.4
  firebase_auth: ^3.3.12
  cloud_firestore: ^3.1.11
  firebase_storage: ^10.2.10
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.13
  image_picker: ^0.8.4+11
  cached_network_image: ^3.2.0
  provider: ^6.0.2
  photo_view: ^0.13.0
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

assets:
  - images/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
