// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATtM9XVrUMJKJiUJsGSFe2yIz5_5-krz0',
    appId: '1:589304575503:web:cfc43e58b131f53c1ed57a',
    messagingSenderId: '589304575503',
    projectId: 'chatapp-6d03f',
    authDomain: 'chatapp-6d03f.firebaseapp.com',
    storageBucket: 'chatapp-6d03f.appspot.com',
    measurementId: 'G-RMHL5YZGR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQDXkILziCjYFhJr0ViZKH_vTCGk-gjIU',
    appId: '1:589304575503:android:66f9cfb8365a6e621ed57a',
    messagingSenderId: '589304575503',
    projectId: 'chatapp-6d03f',
    storageBucket: 'chatapp-6d03f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBeJsFcDuI_RDh6vXTqvV3tgC_qaiX378',
    appId: '1:589304575503:ios:c41eba424e8207771ed57a',
    messagingSenderId: '589304575503',
    projectId: 'chatapp-6d03f',
    storageBucket: 'chatapp-6d03f.appspot.com',
    iosClientId:
        '589304575503-9nk8h1cgruucbgapc46k7bmcanugvs88.apps.googleusercontent.com',
    iosBundleId: 'com.chatapp.app',
  );
}
